version: '3'
services: 
  db:
    image: mysql
    container_name: mysql3
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - 3306:3306
    volumes: 
      - datafile:/var/lib/mysql
  myadmin:
    image: phpmyadmin
    container_name: myadmin3
    ports:
      - 8080:80
volumes:
  datafile:
    driver: local
    